name: ASP.NET Core CI/CD

on:
  push:
    branches:
      - main # yoki sizning asosiy branchingiz
  pull_request:
    branches:
      - main # yoki sizning asosiy branchingiz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # O'zingizning .NET versiyangizni belgilang

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets orqali SSH maxfiy kalit
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no user@62.84.178.136 'bash -s' < ./scripts/deploy.sh
