name: Publish to VPS 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  VPS_USER: ${{ secrets.VPS_USER }}                # VPS foydalanuvchi nomi
  VPS_IP: ${{ secrets.VPS_IP }}                    # VPS IP manzili
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # GitHub Secrets'dan maxfiy SSH kalit
  DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}            # Joylashtiriladigan papka

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./E-Commerce-Bot.sln
        
      - name: Build
        run: dotnet build ./E-Commerce-Bot.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./E-Commerce-Bot.sln --configuration Release --no-build --output './publish'
        
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to VPS
        run: |
          scp -r ./publish/* ${{ env.VPS_USER }}@${{ env.VPS_IP }}:${{ env.DEPLOY_DIR }}/
          ssh -o StrictHostKeyChecking=no ${{ env.VPS_USER }}@${{ env.VPS_IP }} 'bash -s' < ./scripts/deploy.sh
